// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/statistic/service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// StatisticService is a mock of Service interface.
type StatisticService struct {
	ctrl     *gomock.Controller
	recorder *StatisticServiceMockRecorder
}

// StatisticServiceMockRecorder is the mock recorder for StatisticService.
type StatisticServiceMockRecorder struct {
	mock *StatisticService
}

// NewStatisticService creates a new mock instance.
func NewStatisticService(ctrl *gomock.Controller) *StatisticService {
	mock := &StatisticService{ctrl: ctrl}
	mock.recorder = &StatisticServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StatisticService) EXPECT() *StatisticServiceMockRecorder {
	return m.recorder
}
