// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: statistic.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _statistic_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on StudentFormResultRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StudentFormResultRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StudentFormResultRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StudentFormResultRequestMultiError, or nil if none found.
func (m *StudentFormResultRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *StudentFormResultRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetStudentUsername()); l < 4 || l > 30 {
		err := StudentFormResultRequestValidationError{
			field:  "StudentUsername",
			reason: "value length must be between 4 and 30 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetFormId()); err != nil {
		err = StudentFormResultRequestValidationError{
			field:  "FormId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StudentFormResultRequestMultiError(errors)
	}

	return nil
}

func (m *StudentFormResultRequest) _validateUuid(uuid string) error {
	if matched := _statistic_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// StudentFormResultRequestMultiError is an error wrapping multiple validation
// errors returned by StudentFormResultRequest.ValidateAll() if the designated
// constraints aren't met.
type StudentFormResultRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StudentFormResultRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StudentFormResultRequestMultiError) AllErrors() []error { return m }

// StudentFormResultRequestValidationError is the validation error returned by
// StudentFormResultRequest.Validate if the designated constraints aren't met.
type StudentFormResultRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentFormResultRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentFormResultRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentFormResultRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentFormResultRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentFormResultRequestValidationError) ErrorName() string {
	return "StudentFormResultRequestValidationError"
}

// Error satisfies the builtin error interface
func (e StudentFormResultRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentFormResultRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentFormResultRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentFormResultRequestValidationError{}

// Validate checks the field values on StudentFormResultResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StudentFormResultResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StudentFormResultResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StudentFormResultResponseMultiError, or nil if none found.
func (m *StudentFormResultResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *StudentFormResultResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Passed

	if len(errors) > 0 {
		return StudentFormResultResponseMultiError(errors)
	}

	return nil
}

// StudentFormResultResponseMultiError is an error wrapping multiple validation
// errors returned by StudentFormResultResponse.ValidateAll() if the
// designated constraints aren't met.
type StudentFormResultResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StudentFormResultResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StudentFormResultResponseMultiError) AllErrors() []error { return m }

// StudentFormResultResponseValidationError is the validation error returned by
// StudentFormResultResponse.Validate if the designated constraints aren't met.
type StudentFormResultResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StudentFormResultResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StudentFormResultResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StudentFormResultResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StudentFormResultResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StudentFormResultResponseValidationError) ErrorName() string {
	return "StudentFormResultResponseValidationError"
}

// Error satisfies the builtin error interface
func (e StudentFormResultResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStudentFormResultResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StudentFormResultResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StudentFormResultResponseValidationError{}
