// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: statistic.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Statistic_GetStudentFormResult_FullMethodName = "/api.Statistic/GetStudentFormResult"
)

// StatisticClient is the client API for Statistic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticClient interface {
	GetStudentFormResult(ctx context.Context, in *StudentFormResultRequest, opts ...grpc.CallOption) (*StudentFormResultResponse, error)
}

type statisticClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticClient(cc grpc.ClientConnInterface) StatisticClient {
	return &statisticClient{cc}
}

func (c *statisticClient) GetStudentFormResult(ctx context.Context, in *StudentFormResultRequest, opts ...grpc.CallOption) (*StudentFormResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentFormResultResponse)
	err := c.cc.Invoke(ctx, Statistic_GetStudentFormResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticServer is the server API for Statistic service.
// All implementations must embed UnimplementedStatisticServer
// for forward compatibility.
type StatisticServer interface {
	GetStudentFormResult(context.Context, *StudentFormResultRequest) (*StudentFormResultResponse, error)
	mustEmbedUnimplementedStatisticServer()
}

// UnimplementedStatisticServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatisticServer struct{}

func (UnimplementedStatisticServer) GetStudentFormResult(context.Context, *StudentFormResultRequest) (*StudentFormResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentFormResult not implemented")
}
func (UnimplementedStatisticServer) mustEmbedUnimplementedStatisticServer() {}
func (UnimplementedStatisticServer) testEmbeddedByValue()                   {}

// UnsafeStatisticServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticServer will
// result in compilation errors.
type UnsafeStatisticServer interface {
	mustEmbedUnimplementedStatisticServer()
}

func RegisterStatisticServer(s grpc.ServiceRegistrar, srv StatisticServer) {
	// If the following call pancis, it indicates UnimplementedStatisticServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Statistic_ServiceDesc, srv)
}

func _Statistic_GetStudentFormResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentFormResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticServer).GetStudentFormResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Statistic_GetStudentFormResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticServer).GetStudentFormResult(ctx, req.(*StudentFormResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Statistic_ServiceDesc is the grpc.ServiceDesc for Statistic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Statistic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Statistic",
	HandlerType: (*StatisticServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentFormResult",
			Handler:    _Statistic_GetStudentFormResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistic.proto",
}
